### ISSUE TITLE
Add endpoint validation with Joi

### ISSUE THREAD

**Issue by vczb** [mr3saru/telegram-contact-form#3]
Add a simple validation to endpoint `/api/form` using Joi, we suggest [this](https://github.com/arb/celebrate) lib but if you prefer other we are open to discuss

- all the fields are required
- all the fields are string

**Comment by laurittab** [comment]
Hi Vinicius, I'd like to work on this issue using the library you suggested. I've used Joi for work and this one (celebrate) looks good.

**Comment by vczb** [comment]
> Hi Vinicius, I'd like to work on this issue using the library you suggested. I've used Joi for work and this one (celebrate) looks good.

thanks , feel free to work on it

**Comment by laurittab** [comment]
I had to disable the bot in order to run the server. Are already aware of this one?

![bot error](https://github.com/mr3saru/telegram-contact-form/assets/57863817/5cda2085-790d-497d-96c7-97e4e5fc80df)
